import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import type { Explanation, SimilarRule } from "@/lib/types";

function SparkIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" className={className} aria-hidden="true">
      <path
        d="M12 3l1.9 4.7L18.7 9.6 14 11.5 12 16l-2-4.5L5.3 9.6 10.1 7.7 12 3z"
        fill="currentColor"
      />
      <path d="M19 14l.9 2.1L22 17l-2.1.9L19 20l-.9-2.1L16 17l2.1-.9L19 14z" fill="currentColor" opacity="0.7" />
    </svg>
  );
}

interface AiExplanationPanelProps {
  explanation?: Explanation;
  // Present only when no deterministic rule matched anywhere and this decision came
  // from the vector-search + LLM fallback instead.
  aiAssisted?: boolean;
  confidence?: number;
  similarRules?: SimilarRule[];
  // True when no rule matched anywhere AND it's not AI-assisted either — i.e. vector
  // search found nothing confident enough either, so the composite verdict is the
  // configured safe default. The deterministic explainer still runs on this response
  // (it doesn't know why the verdict landed where it did) and can read as a plausible
  // but misleading rationale for a decision no rule actually made — this case gets its
  // own, accurate copy instead.
  noRuleMatched?: boolean;
}

const SAFE_DEFAULT_TEXT =
  "No rule matched anywhere, and nothing in the vector index cleared the confidence threshold either. Rather than guess, the system returned the configured safe default.";

export function AiExplanationPanel({ explanation, aiAssisted, confidence, similarRules, noRuleMatched }: AiExplanationPanelProps) {
  const safeDefault = Boolean(noRuleMatched) && !aiAssisted;
  const full = safeDefault ? SAFE_DEFAULT_TEXT : (explanation?.text ?? "");
  const [shown, setShown] = useState("");

  // Lightweight typewriter — reveals the paragraph a few characters per frame.
  useEffect(() => {
    setShown("");
    if (!full) return;
    let i = 0;
    const step = Math.max(1, Math.round(full.length / 90));
    const timer = setInterval(() => {
      i = Math.min(full.length, i + step);
      setShown(full.slice(0, i));
      if (i >= full.length) clearInterval(timer);
    }, 16);
    return () => clearInterval(timer);
  }, [full]);

  const mode = explanation?.mode ?? "unavailable";
  const isLive = mode === "llm";
  const typing = shown.length < full.length;

  return (
    <div className="relative overflow-hidden rounded-xl border border-border glass p-5 hover-lift">
      {/* shimmering top edge */}
      <div
        className="pointer-events-none absolute inset-x-0 top-0 h-px opacity-70"
        style={{
          background: "linear-gradient(90deg, transparent, var(--brand), transparent)",
          backgroundSize: "200% 100%",
          animation: "shimmer 2.5s linear infinite",
        }}
      />
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="grid h-8 w-8 place-items-center rounded-lg bg-primary/15 text-primary">
            <SparkIcon className="h-4 w-4" />
          </span>
          <div>
            <h3 className="text-sm font-semibold leading-none">
              {aiAssisted ? "AI-assisted recommendation" : safeDefault ? "Safe default applied" : "AI explanation"}
            </h3>
            <p className="mt-1 text-[0.7rem] text-muted-foreground">
              {aiAssisted
                ? "No rule matched — recommended from similar historical rules"
                : safeDefault
                  ? "No rule matched, no confident vector-search match — declined to guess"
                  : "Plain-language rationale from the decision trace"}
            </p>
          </div>
        </div>
        <span
          className={cn(
            "rounded-full border px-2.5 py-1 text-[0.65rem] font-semibold uppercase tracking-wide",
            safeDefault
              ? "border-amber-500/40 bg-amber-500/10 text-amber-600 dark:text-amber-400"
              : isLive
                ? "border-primary/40 bg-primary/10 text-primary"
                : "border-border bg-muted text-muted-foreground",
          )}
          title={safeDefault ? "Configured fallback verdict — no model call" : isLive ? "Generated by the LLM" : "Deterministic offline explainer (no API key)"}
        >
          {safeDefault
            ? "Safe default"
            : isLive
              ? "LLM"
              : mode === "template"
                ? "Deterministic"
                : mode === "heuristic"
                  ? "Heuristic"
                  : "Unavailable"}
        </span>
      </div>

      {aiAssisted && (
        <div className="mt-3 flex flex-wrap items-center gap-2">
          <span className="rounded-full border border-amber-500/40 bg-amber-500/10 px-2.5 py-1 text-[0.65rem] font-semibold uppercase tracking-wide text-amber-600 dark:text-amber-400">
            Vector-search fallback
          </span>
          {confidence !== undefined && (
            <span className="text-[0.7rem] text-muted-foreground">confidence {Math.round(confidence * 100)}%</span>
          )}
        </div>
      )}

      <p className={cn("mt-4 text-sm leading-relaxed text-foreground/90", typing && "typewriter-caret")}>
        {shown || (full ? "" : "No explanation available for this decision.")}
      </p>

      {aiAssisted && similarRules && similarRules.length > 0 && (
        <div className="mt-4 space-y-1.5 border-t border-border pt-3">
          <p className="text-[0.7rem] font-medium text-muted-foreground">Similar rules consulted</p>
          {similarRules.slice(0, 5).map((r) => (
            <div key={`${r.ruleset_id}/${r.rule_id}`} className="flex items-center justify-between gap-2 text-[0.7rem]">
              <span className="truncate font-mono text-muted-foreground">
                {r.ruleset_id}/{r.rule_id} {r.verdict ? `→ ${r.verdict}` : ""}
              </span>
              {r.score !== null && <span className="shrink-0 font-mono text-foreground/70">{r.score.toFixed(2)}</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
